name: Run Pytest and Check Coverage

on:
  push:
    branches:
      - main # Change this to your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Change to your desired Python version

      - name: Install tox
        run: pip install tox

      - name: Run Tox
        run: tox

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
